# Generated by Django 4.2.6 on 2023-10-05 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Disco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
                ("descricao", models.TextField()),
                ("nome_produtora", models.CharField(max_length=50)),
                ("ano", models.DateTimeField()),
                ("pais", models.CharField(max_length=50)),
                (
                    "generos",
                    models.CharField(
                        choices=[
                            ("A", "Eletrônica"),
                            ("B", "Rock"),
                            ("C", "Phonk"),
                            ("D", "jRap"),
                        ],
                        default="A",
                        max_length=30,
                    ),
                ),
                ("quantidade", models.IntegerField()),
            ],
        ),
    ]
