# Generated by Django 4.2.6 on 2023-10-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Artista",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Selo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_produtora", models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(model_name="disco", name="nome_produtora",),
        migrations.AlterField(
            model_name="disco", name="ano", field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="disco",
            name="descricao",
            field=models.TextField(max_length=250),
        ),
        migrations.AddField(
            model_name="disco",
            name="artistas",
            field=models.ManyToManyField(related_name="discos", to="app1.artista"),
        ),
    ]
