# Generated by Django 4.2.6 on 2023-10-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="disco", name="ano", field=models.DateField(),
        ),
    ]
