# Generated by Django 4.2.6 on 2023-10-11 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0002_artista_selo_remove_disco_nome_produtora_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="disco",
            name="selo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app1.selo",
            ),
        ),
    ]
